name: push to server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd app
            ./run.sh
          host: ${{ secrets.HOST }}
          username: kori
          port: 22
          privateKey: ${{ secrets.PRIVATE_KEY }}